[package]
name = "project-leoali"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "gui"
path = "src/gui/main.rs"

[lib]
name = "pika_unixsocket_tools"
path = "src/pika_unixsocket_tools/lib.rs"

[[bin]]
name = "debug_server_update_percent"
path = "src/debug_server/update_percent.rs"

[[bin]]
name = "debug_server_update_status"
path = "src/debug_server/update_status.rs"

[[bin]]
name = "apt_update"
path = "src/apt_update/main.rs"

[[bin]]
name = "apt_get_upgradable"
path = "src/apt_get_upgradable/main.rs"

[dependencies]
adw = { version = "0.5.3", package = "libadwaita", features = ["v1_4"] }
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
async-channel = "2.1.1"
rust-i18n = "3.0.1"
rust-apt = { git = "https://gitlab.com/volian/rust-apt" }
tokio = { version = "1", features = ["full"] }
tokio-uds = "0.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
async-trait = "0.1.80"
futures = "0.3.30"
